### ISSUE TITLE
`json.item.map is not a function` when there is only one item

### ISSUE THREAD

**Issue by TheWeirdDev** [jindra12/react-rss#2]
It took me an hour of debugging and scratching my head but finally I found the reason I was getting this error. When there is exactly one item in the feed, it gets parsed as an object instead of an array, causing the `json.item.map` function call to throw an exception.
Checking for the type of the `item` property and parsing accordingly might fix this.

Thanks for the time you're spending on maintaining this project.

**Comment by jindra12** [comment]
Thank you so much, I'll fix this this month

**Comment by jindra12** [comment]
Issue fixed and closed, sorry, forgot
